export const cities: { title: string }[] = [
    { title: 'Vijay Nagar, Indore' },
    { title: 'Rau, Indore' },
    { title: 'Scheme No 140, Indore' },
    { title: 'Silicon City, Indore' },
    { title: 'Nipania, Indore' },
    { title: 'Rajendra Nagar, Indore' },
    { title: 'Sudama Nagar, Indore' },
    { title: 'Scheme No 114, Indore' },
    { title: 'Mahalakshmi Nagar, Indore' },
    { title: 'Palasia, Indore' },
    { title: 'L I G Colony, Indore' },
    { title: 'Bhicholi Mardana, Indore' },
    { title: 'County Walk Township, Indore' },
    { title: 'Sukhliya, Indore' },
    { title: 'Nagar Nigam, Indore' },
    { title: 'New Rani Bagh, Indore' },
    { title: 'Bengali Square, Indore' },
    { title: 'Scheme 78, Indore' },
    { title: 'Pipliyahana, Indore' },
    { title: 'Vishnu Puri Colony, Indore' },
    { title: 'Sangam Nagar, Indore' },
    { title: 'Manglia, Indore' },
    { title: 'Kalani Nagar, Indore' },
    { title: 'Green Park Colony, Indore' },
    { title: 'Navlakha, Indore' },
    { title: 'Tilak Nagar, Indore' },
    { title: 'IDA Scheme No 134, Indore' },
    { title: 'Indra Puri Colony, Indore' },
    { title: 'Talawali Chanda, Indore' },
    { title: 'Dr. Ambedkar Nagar, Indore' },
    { title: 'Siddhipuram Colony, Indore' },
    { title: 'Nanda Nagar, Indore' },
    { title: 'Vaishali Nagar, Indore' },
    { title: 'Scheme No 71, Indore' },
    { title: 'Old Palasia, Indore' },
    { title: 'Surya Dev Nagar, Indore' },
    { title: 'Kishanganj, Indore' },
    { title: 'Nayta Mundla, Indore' },
    { title: 'Bada Bangarda, Indore' },
    { title: 'Lasudia Mori, Indore' },
    { title: 'Bhawrasla, Indore' },
    { title: 'Karolbagh, Bhawrasla, Indore' },
    { title: 'Bijalpur, Indore' },
    { title: 'Lalaram Nagar, Indore' },
    { title: 'Banganga, Indore' },
    { title: 'Chhota Bangarda, Indore' },
    { title: 'Khajrana, Indore' },
    { title: 'Goyal Vihar, Indore' },
    { title: 'Manishpuri, Indore' },
    { title: 'Tejaji Nagar, Indore' },
    { title: 'Devguradia, Indore' },
    { title: 'Pragati Vihar, Indore' },
    { title: 'Shivaji Nagar, Indore' },
    { title: 'Silver Park Colony, Indore' },
    { title: 'Scheme 103, Indore' },
    { title: 'Indore District, Madhya Pradesh' },
    { title: 'Omex City, Indore' },
    { title: 'Mari Mata Square, Indore' },
    { title: 'Lokmanya Nagar, Indore' },
    { title: 'Brijeshwari Annexe, Indore' },
    { title: 'Sahara City Homes, Indore' },
    { title: 'RRCAT, Indore' },
    { title: 'Kanadiya, Indore' },
    { title: 'Musakhedi, Indore' },
    { title: 'Sanwer Road Industrial Area, Indore' },
    { title: 'Shiv City, Rau, Indore' },
    { title: 'Sai City, Manglia, Indore' },
    { title: 'Limbodi, Indore' },
    { title: 'Nanda Nagar, Indore' },
    { title: 'Manorama Ganj, Indore' },
    { title: 'Malharganj, Indore' },
    { title: 'Shri Ram Nagar, Indore' },
    { title: 'Anoop Nagar, Indore' },
    { title: 'Palsikar Colony, Indore' },
    { title: 'Palakhedi, Indore' },
    { title: 'Pumarth Bliss, Manglia, Indore' },
    { title: 'Dwarkapuri, Indore' },
    { title: 'Devi Ahillyabai Holkar Airport Area, Indore' },
    { title: 'Triveni Colony, Indore' },
    { title: 'Vandana Nagar, Indore' },
    { title: 'Rambag, Indore' },
    { title: 'Bulandshahr, Indore' },
    { title: 'Patni Pura, Indore' },
    { title: 'Devguradia, Indore' },
    { title: 'Life Style Colony, Tigaria Badshah, Indore' },
    { title: 'Vallabh Nagar, Indore' },
    { title: 'Ujjain District, Madhya Pradesh' },
    { title: 'Sanjay Gandhi Nagar, Indore' },
    { title: 'Telephone Nagar, Indore' },
    { title: 'Indore GPO, Indore' },
    { title: 'Palda, Indore' },
    { title: 'Vaibhav Nagar, Indore' },
    { title: 'Shri Nagar, Indore' },
    { title: 'Sanchar Nagar Main, Indore' },
    { title: 'Hatod, Indore' },
    { title: 'Manikbagh, Indore' },
    { title: 'Mhow Gaon, Indore' },
    { title: 'Dewas District, Madhya Pradesh' },
    { title: 'Dudhia, Indore' },
    { title: 'Tigaria Badshah, Indore' },
    { title: 'Shanti Nagar, Mhow, Indore' },
    { title: 'Anuradha Nagar, Indore' },
    { title: 'Asrawad Khurd, Indore' },
    { title: 'Chhoti Gwaltoli, Indore' },
    { title: 'Tukoganj, Indore' },
    { title: 'Raj Mohalla, Indore' },
    { title: 'Malwa County, Manglia, Indore' },
    { title: 'Anurag Nagar, Indore' },
    { title: 'Maharaja Tukoji Rao Holker Cloth Market, Indore' },
    { title: 'Pipliyapala Park IDA Site, Indore' },
    { title: 'Gurukul Colony, Rau, Indore' },
    { title: 'Bada Ganpati, Indore' },
    { title: 'White Church Colony, Indore' },
    { title: 'Laxmibai Nagar, Indore' },
    { title: 'Nagin Nagar, Indore' },
    { title: 'Maya Khedi, Indore' },
    { title: 'Simrol, Indore' },
    { title: 'Nandanvan Colony, Indore' },
    { title: 'Bhangarh, Indore' },
    { title: 'Siyaganj, Indore' },
    { title: 'Harnya Khedi, Indore' },
    { title: 'Dhar Kothi Colony, Indore' },
    { title: 'Budhaniya, Indore' },
    { title: 'Panchsheel Nagar, Indore' },
    { title: 'County Township, Indore' },
    { title: 'Salempur, Indore' },
    { title: 'Datoda, Indore' },
    { title: 'Manavta Nagar, Indore' },
    { title: 'Khatiwala Tank, Indore' },
    { title: 'Kalibillod, Indore' },
    { title: 'Chandra Nagar, Indore' },
    { title: 'Umariya, Indore' },
    { title: 'Sadar Bazar, Indore' },
    { title: 'Industrial Area, Rau, Indore' },
    { title: 'Chandan Nagar, Indore' },
    { title: 'Navin Colony, Mhow, Indore' },
    { title: 'Magar Kheda, Indore' },
    { title: 'Paliya Haidar, Indore' },
    { title: 'Chhatribagh, Indore' },
    { title: 'Scheme No 94C, Indore' },
    { title: 'Rajmahal Colony, Indore' },
    { title: 'Lavisha Singapur Township, Indore' },
    { title: 'Thakur Colony, Rau, Indore' },
    { title: 'Ringnodiya, Indore' },
    { title: 'Jakhya, Indore' },
    { title: 'Azad Nagar, Indore' },
    { title: 'Palakhedi, Indore' },
    { title: 'Agrasen Nagar, Indore' },
    { title: 'Bhagirath Colony, Mhow, Indore' },
    { title: 'Sector B, Rau, Indore' },
    { title: 'Tigaria Rao, Indore' },
    { title: 'Sanvid Nagar, Indore' },
    { title: 'Tejpur Gadbadi, Indore' },
    { title: 'Panda, Indore' },
    { title: 'Baikunth Dham, Indore' },
    { title: 'Mirjapur, Indore' },
    { title: 'Arandia, Indore' },
    { title: 'Kelod Kartal, Indore' },
    { title: 'Niranjanpur, Indore' },
    { title: 'Phase 2, Indore' },
    { title: 'Depalpur, Indore' },
    { title: 'Panchderiya, Indore' },
    { title: 'Gokanya, Indore' },
    { title: 'Saptshrangi Nagar, Rau, Indore' },
    { title: 'Ram Rahim Colony, Rau, Indore' },
    { title: 'Krishi Mandi, Indore' },
    { title: 'Sanawadia, Indore' },
    { title: 'Sanwer, Indore' },
    { title: 'Nai Duniya, Indore' },
    { title: 'Barfani, Indore' },
    { title: 'Morod, Indore' },
    { title: 'Hasalpur, Indore' },
    { title: 'Banjari, Dhar' },
    { title: 'Dream City Ashiyana, Palakhedi, Indore' },
    { title: 'Industrial Estate, Indore' },
    { title: 'Sinhasa, Indore' },
    { title: 'Transport Nagar, Indore' },
    { title: 'Bhangiya, Indore' },
    { title: 'Bhatkhedi, Indore District' },
    { title: 'Borkhedi, Indore' },
    { title: 'Methwada, Indore' },
    { title: 'Choral, Indore' },
    { title: 'Roopram Nagar, Indore' },
    { title: 'Vindhyanchal Nagar, Indore' },
    { title: 'Mahal Kacheri, Indore' },
    { title: 'Dharnaka, Indore' },
    { title: 'Devi Ahilya Vishwa Vidyalaya, Indore' },
    { title: 'Murai Mohalla, Indore' },
    { title: 'Songir, Indore' },
    { title: 'Bagoda, Indore' },
    { title: 'Pirkaradiya, Indore' },
    { title: 'Mundla Bag, Indore' },
    { title: 'Loknayak Nagar, Indore' },
    { title: 'Bhangya, Indore' },
    { title: 'Ala Pura Indore, Madhya Pradesh, Indore' },
    { title: 'Sirpur, Indore' },
    { title: 'Royal Town, Mhow, Indore' },
    { title: 'Muradpura, Indore' },
    { title: 'Badipura, Indore' },
    { title: 'Gram Baroli, Indore' },
    { title: 'Balya Kheda, Indore' },
    { title: 'Suman Colony, Mhow, Indore' },
    { title: 'Runji Gautampura, Indore' },
    { title: 'Durga Colony, Indore' },
    { title: 'Kodriya, Indore' }
  ];